FROM frolvlad/alpine-glibc:latest

ENV OC_CLI_URL mirror.openshift.com/pub/openshift-v3/clients
ENV OC_CLI_DEFAULT_VERSION 3.10.0-0.13.0
ENV OC_CLI_OS linux/oc.tar.gz

RUN apk add --no-cache --virtual .build-deps \
        curl \
        tar \
    && curl --retry 7 -Lo /tmp/client-tools.tar.gz "https://$OC_CLI_URL/$OC_CLI_DEFAULT_VERSION/$OC_CLI_OS"

RUN tar zxf /tmp/client-tools.tar.gz -C /usr/local/bin oc \
    && rm /tmp/client-tools.tar.gz \
    && apk del .build-deps

# ADDED: Resolve issue x509 oc login issue
RUN apk add --update ca-certificates