apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob-can-read-pods
subjects:
- kind: User
  name: bob
  namespace: dev
roleRef:
  kind: Role
  name: podviewer
  apiGroup: rbac.authorization.k8s.io